[2022-12-22 09:05:45,632] INFO [GroupCoordinator 0]: Member console-consumer-df9d17b5-c54f-40ff-8999-4065ebfbe276 in group console-consumer-67146 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2022-12-22 09:05:45,738] INFO Expiring session 0x1000009358e0005, timeout of 18000ms exceeded (org.apache.zookeeper.server.ZooKeeperServer)
[2022-12-22 09:05:45,741] WARN Attempting to send response via channel for which there is no open connection, connection id 127.0.0.1:9092-127.0.0.1:52858-13 (kafka.network.Processor)
[2022-12-22 09:05:46,444] WARN Client session timed out, have not heard from server in 45370205ms for session id 0x1000009358e0005 (org.apache.zookeeper.ClientCnxn)
[2022-12-22 09:05:46,210] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-67146 in state PreparingRebalance with old generation 10 (__consumer_offsets-45) (reason: removing member console-consumer-df9d17b5-c54f-40ff-8999-4065ebfbe276 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2022-12-22 09:05:46,840] WARN Session 0x1000009358e0005 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 45370205ms for session id 0x1000009358e0005
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
[2022-12-22 09:05:46,987] INFO [GroupCoordinator 0]: Group console-consumer-67146 with generation 11 is now empty (__consumer_offsets-45) (kafka.coordinator.group.GroupCoordinator)
[2022-12-22 09:05:47,009] INFO [GroupCoordinator 0]: Dynamic member with unknown member id joins group console-consumer-67146 in Empty state. Created a new member id console-consumer-44fc88af-75c7-4118-9ce7-171cef810500 and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
[2022-12-22 09:05:47,011] INFO [GroupCoordinator 0]: Preparing to rebalance group console-consumer-67146 in state PreparingRebalance with old generation 11 (__consumer_offsets-45) (reason: Adding new member console-consumer-44fc88af-75c7-4118-9ce7-171cef810500 with group instance id None; client reason: rebalance failed due to MemberIdRequiredException) (kafka.coordinator.group.GroupCoordinator)
[2022-12-22 09:05:47,012] INFO [GroupCoordinator 0]: Stabilized group console-consumer-67146 generation 12 (__consumer_offsets-45) with 1 members (kafka.coordinator.group.GroupCoordinator)
[2022-12-22 09:05:47,015] INFO [GroupCoordinator 0]: Assignment received from leader console-consumer-44fc88af-75c7-4118-9ce7-171cef810500 for group console-consumer-67146 for generation 12. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
[2022-12-22 09:05:48,451] INFO Opening socket connection to server localhost/127.0.0.1:2181. (org.apache.zookeeper.ClientCnxn)
[2022-12-22 09:05:48,486] INFO Socket connection established, initiating session, client: /127.0.0.1:50860, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn)
[2022-12-22 09:05:48,532] INFO Invalid session 0x1000009358e0005 for client /127.0.0.1:50860, probably expired (org.apache.zookeeper.server.ZooKeeperServer)
[2022-12-22 09:05:48,543] WARN Unable to reconnect to ZooKeeper service, session 0x1000009358e0005 has expired (org.apache.zookeeper.ClientCnxn)
[2022-12-22 09:05:48,562] WARN Session 0x1000009358e0005 for sever localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
org.apache.zookeeper.ClientCnxn$SessionExpiredException: Unable to reconnect to ZooKeeper service, session 0x1000009358e0005 has expired
	at org.apache.zookeeper.ClientCnxn$SendThread.onConnected(ClientCnxn.java:1434)
	at org.apache.zookeeper.ClientCnxnSocket.readConnectResult(ClientCnxnSocket.java:154)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:86)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
[2022-12-22 09:05:48,544] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2022-12-22 09:05:48,544] INFO EventThread shut down for session: 0x1000009358e0005 (org.apache.zookeeper.ClientCnxn)
[2022-12-22 09:05:48,564] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2022-12-22 09:05:48,564] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@6ad59d92 (org.apache.zookeeper.ZooKeeper)
[2022-12-22 09:05:48,566] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2022-12-22 09:05:48,566] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
[2022-12-22 09:05:48,581] INFO Opening socket connection to server localhost/127.0.0.1:2181. (org.apache.zookeeper.ClientCnxn)
[2022-12-22 09:05:48,584] INFO Socket connection established, initiating session, client: /127.0.0.1:50863, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn)
[2022-12-22 09:05:48,586] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.zk.KafkaZkClient)
[2022-12-22 09:05:48,589] INFO Session establishment complete on server localhost/127.0.0.1:2181, session id = 0x1000009358e0006, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2022-12-22 09:05:48,592] INFO [MetadataCache brokerId=0] Updated cache from existing FinalizedFeaturesAndEpoch(features=Map(), epoch=0) to latest FinalizedFeaturesAndEpoch(features=Map(), epoch=0). (kafka.server.metadata.ZkMetadataCache)
[2022-12-22 09:05:48,595] INFO Stat of the created znode at /brokers/ids/0 is: 226,226,1671710748590,1671710748590,1,0,0,72057633591132166,238,0,226
 (kafka.zk.KafkaZkClient)
[2022-12-22 09:05:48,595] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT://EZE1-LLN-B02023.synapse.com:9092, czxid (broker epoch): 226 (kafka.zk.KafkaZkClient)
[2022-12-22 16:56:08,155] INFO [LocalLog partition=HelloTopic-0, dir=c:\kafka\kafka-logs] Rolled new log segment at offset 6 in 11 ms. (kafka.log.LocalLog)
[2022-12-22 16:56:08,167] INFO [ProducerStateManager partition=HelloTopic-0] Wrote producer snapshot at offset 6 with 0 producer ids in 9 ms. (kafka.log.ProducerStateManager)
[2022-12-22 16:56:08,174] INFO [UnifiedLog partition=HelloTopic-0, dir=c:\kafka\kafka-logs] Deleting segment LogSegment(baseOffset=0, size=483, lastModifiedTime=1671134065769, largestRecordTimestamp=Some(1671134065737)) due to retention time 604800000ms breach based on the largest record timestamp in the segment (kafka.log.UnifiedLog)
[2022-12-22 16:56:08,180] ERROR Error while deleting segments for HelloTopic-0 in dir c:\kafka\kafka-logs (kafka.server.LogDirFailureChannel)
java.nio.file.FileSystemException: c:\kafka\kafka-logs\HelloTopic-0\00000000000000000000.timeindex -> c:\kafka\kafka-logs\HelloTopic-0\00000000000000000000.timeindex.deleted: The process cannot access the file because it is being used by another process.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:395)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
	at java.base/java.nio.file.Files.move(Files.java:1422)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:935)
	at kafka.log.AbstractIndex.renameTo(AbstractIndex.scala:210)
	at kafka.log.LazyIndex$IndexValue.renameTo(LazyIndex.scala:155)
	at kafka.log.LazyIndex.$anonfun$renameTo$1(LazyIndex.scala:79)
	at kafka.log.LazyIndex.renameTo(LazyIndex.scala:79)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:493)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1(LocalLog.scala:989)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1$adapted(LocalLog.scala:987)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.LocalLog$.deleteSegmentFiles(LocalLog.scala:987)
	at kafka.log.LocalLog.removeAndDeleteSegments(LocalLog.scala:314)
	at kafka.log.UnifiedLog.$anonfun$deleteSegments$2(UnifiedLog.scala:1385)
	at kafka.log.UnifiedLog.deleteSegments(UnifiedLog.scala:1752)
	at kafka.log.UnifiedLog.deleteRetentionMsBreachedSegments(UnifiedLog.scala:1364)
	at kafka.log.UnifiedLog.deleteOldSegments(UnifiedLog.scala:1403)
	at kafka.log.LogManager.$anonfun$cleanupLogs$3(LogManager.scala:1236)
	at kafka.log.LogManager.$anonfun$cleanupLogs$3$adapted(LogManager.scala:1233)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.LogManager.cleanupLogs(LogManager.scala:1233)
	at kafka.log.LogManager.$anonfun$startupWithConfigOverrides$2(LogManager.scala:528)
	at kafka.utils.KafkaScheduler.$anonfun$schedule$2(KafkaScheduler.scala:116)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.nio.file.FileSystemException: c:\kafka\kafka-logs\HelloTopic-0\00000000000000000000.timeindex -> c:\kafka\kafka-logs\HelloTopic-0\00000000000000000000.timeindex.deleted: The process cannot access the file because it is being used by another process.

		at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
		at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:309)
		at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
		at java.base/java.nio.file.Files.move(Files.java:1422)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:932)
		... 26 more
[2022-12-22 16:56:08,188] WARN [ReplicaManager broker=0] Stopping serving replicas in dir c:\kafka\kafka-logs (kafka.server.ReplicaManager)
[2022-12-22 16:56:08,188] ERROR Uncaught exception in scheduled task 'kafka-log-retention' (kafka.utils.KafkaScheduler)
org.apache.kafka.common.errors.KafkaStorageException: Error while deleting segments for HelloTopic-0 in dir c:\kafka\kafka-logs
Caused by: java.nio.file.FileSystemException: c:\kafka\kafka-logs\HelloTopic-0\00000000000000000000.timeindex -> c:\kafka\kafka-logs\HelloTopic-0\00000000000000000000.timeindex.deleted: The process cannot access the file because it is being used by another process.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:395)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
	at java.base/java.nio.file.Files.move(Files.java:1422)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:935)
	at kafka.log.AbstractIndex.renameTo(AbstractIndex.scala:210)
	at kafka.log.LazyIndex$IndexValue.renameTo(LazyIndex.scala:155)
	at kafka.log.LazyIndex.$anonfun$renameTo$1(LazyIndex.scala:79)
	at kafka.log.LazyIndex.renameTo(LazyIndex.scala:79)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:493)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1(LocalLog.scala:989)
	at kafka.log.LocalLog$.$anonfun$deleteSegmentFiles$1$adapted(LocalLog.scala:987)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.LocalLog$.deleteSegmentFiles(LocalLog.scala:987)
	at kafka.log.LocalLog.removeAndDeleteSegments(LocalLog.scala:314)
	at kafka.log.UnifiedLog.$anonfun$deleteSegments$2(UnifiedLog.scala:1385)
	at kafka.log.UnifiedLog.deleteSegments(UnifiedLog.scala:1752)
	at kafka.log.UnifiedLog.deleteRetentionMsBreachedSegments(UnifiedLog.scala:1364)
	at kafka.log.UnifiedLog.deleteOldSegments(UnifiedLog.scala:1403)
	at kafka.log.LogManager.$anonfun$cleanupLogs$3(LogManager.scala:1236)
	at kafka.log.LogManager.$anonfun$cleanupLogs$3$adapted(LogManager.scala:1233)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at kafka.log.LogManager.cleanupLogs(LogManager.scala:1233)
	at kafka.log.LogManager.$anonfun$startupWithConfigOverrides$2(LogManager.scala:528)
	at kafka.utils.KafkaScheduler.$anonfun$schedule$2(KafkaScheduler.scala:116)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.nio.file.FileSystemException: c:\kafka\kafka-logs\HelloTopic-0\00000000000000000000.timeindex -> c:\kafka\kafka-logs\HelloTopic-0\00000000000000000000.timeindex.deleted: The process cannot access the file because it is being used by another process.

		at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
		at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:309)
		at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
		at java.base/java.nio.file.Files.move(Files.java:1422)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:932)
		... 26 more
[2022-12-22 16:56:08,191] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions HashSet(__consumer_offsets-22, __consumer_offsets-30, __consumer_offsets-35, __consumer_offsets-37, __consumer_offsets-38, __consumer_offsets-13, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, __consumer_offsets-46, quickstart-events-0, __consumer_offsets-25, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, __consumer_offsets-42, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-15, __consumer_offsets-24, __consumer_offsets-17, __consumer_offsets-48, __consumer_offsets-19, __consumer_offsets-11, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, HelloTopic-0, __consumer_offsets-14, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, __consumer_offsets-12, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaFetcherManager)
[2022-12-22 16:56:08,192] INFO [ReplicaAlterLogDirsManager on broker 0] Removed fetcher for partitions HashSet(__consumer_offsets-22, __consumer_offsets-30, __consumer_offsets-35, __consumer_offsets-37, __consumer_offsets-38, __consumer_offsets-13, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, __consumer_offsets-46, quickstart-events-0, __consumer_offsets-25, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, __consumer_offsets-42, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-15, __consumer_offsets-24, __consumer_offsets-17, __consumer_offsets-48, __consumer_offsets-19, __consumer_offsets-11, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, HelloTopic-0, __consumer_offsets-14, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, __consumer_offsets-12, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaAlterLogDirsManager)
[2022-12-22 16:56:08,211] WARN [ReplicaManager broker=0] Broker 0 stopped fetcher for partitions __consumer_offsets-22,__consumer_offsets-30,__consumer_offsets-35,__consumer_offsets-37,__consumer_offsets-38,__consumer_offsets-13,__consumer_offsets-8,__consumer_offsets-21,__consumer_offsets-4,__consumer_offsets-27,__consumer_offsets-7,__consumer_offsets-9,__consumer_offsets-46,quickstart-events-0,__consumer_offsets-25,__consumer_offsets-41,__consumer_offsets-33,__consumer_offsets-23,__consumer_offsets-49,__consumer_offsets-47,__consumer_offsets-16,__consumer_offsets-28,__consumer_offsets-31,__consumer_offsets-36,__consumer_offsets-42,__consumer_offsets-3,__consumer_offsets-18,__consumer_offsets-15,__consumer_offsets-24,__consumer_offsets-17,__consumer_offsets-48,__consumer_offsets-19,__consumer_offsets-11,__consumer_offsets-2,__consumer_offsets-43,__consumer_offsets-6,HelloTopic-0,__consumer_offsets-14,__consumer_offsets-20,__consumer_offsets-0,__consumer_offsets-44,__consumer_offsets-39,__consumer_offsets-12,__consumer_offsets-45,__consumer_offsets-1,__consumer_offsets-5,__consumer_offsets-26,__consumer_offsets-29,__consumer_offsets-34,__consumer_offsets-10,__consumer_offsets-32,__consumer_offsets-40 and stopped moving logs for partitions  because they are in the failed log directory c:\kafka\kafka-logs. (kafka.server.ReplicaManager)
[2022-12-22 16:56:08,213] WARN Stopping serving logs in dir c:\kafka\kafka-logs (kafka.log.LogManager)
[2022-12-22 16:56:08,220] ERROR Shutdown broker because all log dirs in c:\kafka\kafka-logs have failed (kafka.log.LogManager)
